# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:3.9.6
stages:
- test
- run
- package
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
test:
  stage: test
  script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - echo "TEST"
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - coverage run ModelsTest.py
  - coverage report -m
run:
  stage: run
  script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - python test.py
docker:
  tags:
  - shell
  stage: package
  only:
  - master
  script:
  - echo "package docker"
  - docker info
  - docker login -u echo0821 -p Lkq2mapp565688 registry.hub.docker.com
  - docker build -t registry.hub.docker.com/echo0821/web-methodology:latest .
  - docker push registry.hub.docker.com/echo0821/web-methodology:latest
  - docker rmi registry.hub.docker.com/echo0821/web-methodology
sast:
  variables:
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, editormd
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
