"""empty message

Revision ID: 22aedb042a27
Revises: 14b5d4ff2114
Create Date: 2020-12-23 14:04:15.123460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aedb042a27'
down_revision = '14b5d4ff2114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shared_from', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('shared_from')
        batch_op.drop_column('shared_content')

    # ### end Alembic commands ###
